server:
  port: 0

# Spring
spring:
  application:
    name: access-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/access-service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Eureka Service Discovery SignUp
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

